- name: conditions
  hosts: local
  connection: local
  vars:
    number: 12
  tasks:
  - name: comparing numbers
    ansible.builtin.debug:
     msg: "Given number {{ number }} is grater than 10"
    when: number < 10
  
  # - name: comparing numbers
  #   ansible.builtin.debug:
  #    msg: "Given number {{ number }} is equal to 10"
  #   when: number = 10