- name: Install and start nginx
  hosts: web
  become: yes # -b == Root user
  tasks:
    - name: Dowbload nginx
      ansible.builtin.package:
        name: ngnix
        state: present
    - name: Install nginx
      ansible.builtin.package:
        name: ngnix
        state: started
        status: yes
