- name: Install and start Ngnix
  hosts: web
  becoms: yes # -b == root user
  tasks: Install Ngnix
  - name:
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start Ngnix
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
