- name: Install and run nginx
  hosts: web
  become: yes # -b == Root user
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: ngnix
        state: present
    - name: start nginx
      ansible.builtin.package:
        name: ngnix
        state: started
        status: yes
