- name: Install and start nginx
  hosts: web
  become: yes # -b == Root user
  tasks:
    - name: Dowbload nginx
      ansible.builtin.package:
        name: ansible
        state: present
    - name: Install nginx
      ansible.builtin.package:
        name: ansible
        state: insttalled
        status: yes
