- name: variables
  hosts: local
  connection: local
  vars:
    name: "AshokKumar Simhadri"
    designation: "DevOps Engineer"
    Org: "Value Momentum"
  tasks:
  - name: calling variables
    ansible.builtin.debug:
      msg: "This is {{ name }}, who is working as {{ designation }} at {{ Org }}"